# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/rova/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/rova

# Usage:
#  - copy file(s) from proprietary/vendor/ to $(TARGET_COPY_OUT_VENDOR)
#    NOTE: separate files by space:
#      $(call copy-vendor-files, vendor/lib/file1 vendor/lib/file2 ...)
#
#  - Same pattern for other functions:
#      copy-system-files     => will copy to TARGET_COPY_OUT_SYSTEM
#      copy-system-ext-files => will copy to TARGET_COPY_OUT_SYSTEM_EXT
#      copy-product-files    => will copy to TARGET_COPY_OUT_PRODUCT
copy-file = $(eval PRODUCT_COPY_FILES += vendor/xiaomi/rova/proprietary/$(1):$(2))
copy-files = $(foreach blob,$(1),$(call copy-file,$(2)/$(blob),$(3)/$(blob)))
copy-vendor-files = $(call copy-files,$(1),vendor,$(TARGET_COPY_OUT_VENDOR))
copy-system-files = $(call copy-files,$(1),system,$(TARGET_COPY_OUT_SYSTEM))
copy-system-ext-files = $(call copy-files,$(1),system_ext,$(TARGET_COPY_OUT_SYSTEM_EXT))
copy-product-files = $(call copy-files,$(1),product,$(TARGET_COPY_OUT_PRODUCT))

VENDOR_MAP_LIST := \
                   audio \
                   bluetooth \
                   camera \
                   connectivity \
                   crypto \
                   gps \
                   graphics \
                   media \
                   misc \
                   qualcomm \
                   sensors
$(foreach p, $(VENDOR_MAP_LIST), $(call inherit-product, vendor/xiaomi/rova/map/$(p).mk))
